name: cosmos_dart
description: Pure Dart library to easily integrate with any Cosmos-based chain.
version: 1.0.0
homepage: https://github.com/fxwalletOfficial/cosomos_dart.dart
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  asn1lib: ^1.0.0
  bech32: ^0.2.0
  bip39: ^1.0.6
  convert: ^3.0.0
  equatable: ^2.0.0
  fixnum: ^1.0.0
  hex: ^0.2.0
  json_annotation: ^4.4.0
  json_serializable: ^6.2.0
  meta: ^1.3.0
  pointycastle: ^3.0.1
  protobuf: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.11
  test: ^1.16.8
  lints: ^2.1.0
